# Args: <obj_file> <output_dir>
{
  "version": 2,
  "setup": {
    "blender_install_path": "/home/<env:USER>/blender/",
    "pip": [
    ]
  },
  "global": {
    "all": {
      "output_dir": "<args:1>"
    }
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config": {}
    },
    {
      "module": "loader.ObjectLoader",
      "config": {
        "path": "<args:0>"
      }
    },
    {
      "module": "loader.ObjectLoader",
      "config": {
        "path": "<args:2>"
      }
    },
    {
      "module": "lighting.LightLoader",
      "config": {
        "lights": [
          {
            "type": "POINT",
            "location": [5, -5, 5],
            "energy": 1000
          }
        ]
      }
    },


    {
      "module": "composite.CameraObjectTrajRunner",
      "config": {
        "n_frames": 5,
        "object_runner": {
          "module": "object.ObjectTrajectoryRunner",
          "config": {
            "target_names": ['m1'],
            "poses": {
              "locations": 
              [
                [-1, -10, 0.5],
                [0, -10, 1.0],
                [1, -10, 1.5],
                [2, -10, 2.0],
                [3, -10, 2.5],
              ],
              "rotations": 
              [
                [0.05, 0, 0],
                [0.05, 0.1, 0],
                [0.05, 0, 0.1],
                [0.05, 0, 0.1],
                [0.05, 0, 0.1],
              ],
            },
          }
        },
        "camera_runner": {
          "module": "camera.CameraTrajectoryRunner",
          "config": {
            "intrinsics": {
              "resolution_x": 640,
              "resolution_y": 480,
            },
            "cam_poses": {
              "locations":
                [
                  [0, -20, 4],
                  [1, -20, 4],
                  [2, -20, 4],
                  [3, -20, 4],
                  [4, -20, 4],
                ],
              "forward_vec": 
                [
                  [0, 1, -0.2],
                  [0, 1, -0.2],
                  [0, 1, -0.2],
                  [0, 1, -0.2],
                  [0, 1, -0.2],
                ],
              }
            }
          }
        }
    },

    {
      "module": "renderer.SimRgbRenderer",
      "config": {
        "resolution_x": 640,
        "resolution_y": 480,
        "output_key": "colors"
      }
    },
    {
      "module": "renderer.SegMapPngRenderer",
      "config": {
        "resolution_x": 640,
        "resolution_y": 480,
        "map_by": "instance"
      }
    },
    {
      "module": "writer.RGBSegWriter",
      "config": {
      }
    }
  ]
}
