# Args: <obj_file> <output_dir>
{
  "version": 2,
  "setup": {
    "blender_install_path": "/home/<env:USER>/blender/",
    "pip": [
    ]
  },
  "global": {
    "all": {
      "output_dir": "<args:2>"
    }
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config": {}
    },
    {
      "module": "loader.ObjectLoader",
      "config": {
        "path": "<args:0>"
      }
    },

    {
      "module": "composite.VOSTrajRunner",
      "config": {
        "n_frames": 5,
        "camera_runner": {
          "module": "camera.CameraTrajectoryRunner",
          "config": {
            "intrinsics": {
              "resolution_x": 640,
              "resolution_y": 480,
            },
            "cam_poses": {
              "locations":
                [
                  [0, -20, 4],
                  [1, -20, 4],
                  [2, -20, 4],
                  [3, -20, 4],
                  [4, -20, 4],
                ],
              "forward_vec": 
                [
                  [0, 1, -0.2],
                  [0, 1, -0.2],
                  [0, 1, -0.2],
                  [0, 1, -0.2],
                  [0, 1, -0.2],
                ],
            }
          }
        },
        "object_runners": [
          {
            "module": "object.ObjectTrajectoryRunner",
            "config": {
              "path": "<args:1>",
              "scale": [1.5, 1.5, 1.5],
              "poses": {
                "locations": 
                [
                  [-1, -10, 0.5],
                  [0, -10, 1.0],
                  [1, -10, 1.5],
                  [2, -10, 2.0],
                  [3, -10, 2.5],
                ],
                "rotations": 
                [
                  [0.05, 0, 0],
                  [0.05, 0.1, 0],
                  [0.05, 0, 0.1],
                  [0.05, 0, 0.1],
                  [0.05, 0, 0.1],
                ],
              },
            }
          },

          {
            "module": "object.ObjectTrajectoryRunner",
            "config": {
              "path": "<args:1>",
              "scale": [2.5, 2.5, 2.5],
              "poses": {
                "locations": 
                [
                  [4, -5, 0.5],
                  [3, -5, 1.0],
                  [2, -5, 1.5],
                  [1, -5, 2.0],
                  [2, -5, 2.5],
                ],
                "rotations": 
                [
                  [0.05, 1, 0],
                  [0.05, 1, 0],
                  [0.05, 1, 0.1],
                  [0.05, 1, 0.1],
                  [0.05, 1, 0.1],
                ],
              },
            }
          },
        ],
        "light_runners": [
          {
            "module": "lighting.LightTrajectoryRunner",
            "config": {
              "name": 'light1',
              "light": {
                "type": "POINT",
                "energy": 1000
              },
              "poses": {
                "locations": 
                [
                  [5, -5, 5],
                  [6, -5, 5],
                  [7, -5, 5],
                  [2, -5, 5],
                  [3, -5, 5],
                ],
                "rotations": 
                [
                  [0.05, 0, 0],
                  [0.05, 0.1, 0],
                  [0.05, 0, 0.1],
                  [0.05, 0, 0.1],
                  [0.05, 0, 0.1],
                ],
              },
            }
          },
        ]
      }
    },

    {
      "module": "renderer.SimRgbRenderer",
      "config": {
        "resolution_x": 640,
        "resolution_y": 480,
        "output_key": "colors"
      }
    },
    {
      "module": "renderer.SegMapPngRenderer",
      "config": {
        "resolution_x": 640,
        "resolution_y": 480,
        "map_by": "instance"
      }
    },
    {
      "module": "writer.RGBSegWriter",
      "config": {
      }
    }
  ]
}
