# Args: <obj_file> <output_dir>
{
  "version": 2,
  "setup": {
    "blender_install_path": "/home_local/<env:USER>/blender/",
    "pip": [
    ]
  },
  "global": {
    "all": {
      "output_dir": "<args:1>"
    }
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config": {}
    },
    {
      "module": "loader.ObjectLoader",
      "config": {
        "path": "<args:0>"
      }
    },
    {
      "module": "lighting.LightLoader",
      "config": {
        "lights": [
          {
            "type": "POINT",
            "location": [5, -5, 5],
            "energy": 1000
          }
        ]
      }
    },


    {
      "module": "composite.CameraObjectTrajRunner",
      "config": {
        "total_noof_cams": 20,
        "noof_cams_per_scene": 1,
        "object_pose_sampler": {
          "module": "object.ObjectFixedPoseSampler",
          "config": {
            "poses": [
            {
              "location": [0.05, -0.05, 0.05],
              "rotation": [0.05, 0, 0]
            },
            {
              "location": [0.05, 0.05, 0.05],
              "rotation": [0.05, 0.1, 0]
            },
            {
              "location": [0.15, 0.05, 0.075],
              "rotation": [0.05, 0, 0.1]
            }
            ],
          }
        },
        "camera_pose_sampler": {
          "module": "camera.CameraSampler",
          "config": {
            "cam_poses": [
            {
              "location": [0, -13, 4],
              "rotation": {
                "value":[1.3, 0.2, 0]
              }
            },
            ],
          }
        }
      }
    },

    # {
    #   "module": "camera.CameraLoader",
    #   "config": {
    #     "cam_poses": [
    #     {
    #       "location": [0, -13, 4],
    #       "rotation": {
    #         "value":[1.3, 0, 0]
    #       }
    #     },
    #     {
    #       "location": [0, -13, 4],
    #       "rotation": {
    #         "value": [1.3, 0, 0]
    #       }
    #     },
    #     {
    #       "location": [0, -13, 4],
    #       "rotation": {
    #         "value": [1.3, 0, 0]
    #     }
    #     }
    #     ],
    #     "default_cam_param": {
    #       "fov": 1
    #     }
    #   }
    # },
    # {
    #   "module": "object.EntityManipulator",
    #   "config": {
    #     "selector": {
    #       "provider": "getter.Entity",
    #       "conditions": {
    #         "name": 'Suzanne',
    #         "type": "MESH"  # this guarantees that the object is a mesh, and not for example a camera
    #       }
    #     },
    #     "location": {
    #       "provider": "sampler.Uniform3d",
    #       "max":[1, 2, 3],
    #       "min":[0, 1, 2]
    #     },
    #     # "location": [
    #     #   {
    #     #     [1, 2, 3],
    #     #     [0, 1, 2],
    #     #   },
    #     # ],
    #     # "location": [
    #     #   "value": [1, 2, 3],
    #     #   "value": [1, 1, 3],
    #     # ],
    #     "rotation_euler": [1, 1, 0],
    #     "physics": False
    #   }
    # },
    # {
    #   "module": "object.ObjectPoseSampler",
    #   "config":{
    #     "objects_to_sample": {
    #       "provider": "getter.Entity",
    #       "conditions": {
    #         "name": 'Suzanne',
    #         "type": "MESH"
    #       }
    #     },
    #     "pos_sampler":{
    #       "provider":"sampler.Uniform3d",
    #       "max":[1, 1, 1],
    #       "min":[-1, -1, 1]
    #     },
    #     "rot_sampler":{
    #       "provider":"sampler.Uniform3d",
    #       "max":[1, 1, 1],
    #       "min":[0, 0, 0]
    #     }
    #   }
    # },

    {
      "module": "renderer.SimRgbRenderer",
      "config": {
        "output_key": "colors"
      }
    },
    {
      "module": "renderer.SegMapPngRenderer",
      "config": {
        "map_by": "instance"
      }
    },
    {
      "module": "writer.RGBSegWriter",
      "config": {
      }
    }
  ]
}
